- hosts: tomcat_servers
  become: yes

  tasks:
    - name: install java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: download tomcat from dlcdn
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.111/bin/apache-tomcat-9.0.111.tar.gz
        dest: /opt/apache-tomcat-9.0.111.tar.gz

    - name: untar the apache tomcat file
      unarchive:
        src: /opt/apache-tomcat-9.0.111.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/apache-tomcat-9.0.111

    - name: rename the tomcat
      command: mv /opt/apache-tomcat-9.0.111 /opt/tomcat
      args:
        creates: /opt/tomcat
      tags: abc

    - name: set roles in tomcat-users.xml
      template:
        src: tomcat-users.xml
        dest: /opt/tomcat/conf/tomcat-users.xml
      notify: restart tomcat

    - name: remove restriction in context.xml
      template:
        src: context.xml
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml
      notify: restart tomcat

    - name: start tomcat
      command: /opt/tomcat/bin/startup.sh
      args:
        creates: /opt/tomcat/logs/catalina.out

  handlers:
    - name: restart tomcat
      command: /opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh

