- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.111/bin/apache-tomcat-9.0.111.tar.gz
        dest: /root/apache-tomcat-9.0.111.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /root/apache-tomcat-9.0.111.tar.gz
        dest: /root/
        remote_src: yes

    - name: Rename Tomcat directory
      command: mv /root/apache-tomcat-9.0.111 /root/tomcat
      args:
        creates: /root/tomcat

    - name: Install Java 8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Configure tomcat users
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: Configure manager context
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: Start Tomcat
      shell: nohup /root/tomcat/bin/startup.sh
